name: Deploy on fly.io [PRD]
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]'
jobs:
  deploy:
    name: Deploy proxy
    runs-on: ubuntu-latest
    steps:
      # check out repository and flyctl deploy
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --app doraemon-app-db-migration
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
